[package]
name = "nft_ingester"
version = "0.7.12"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.53"
base64 = "0.21.0"
blockbuster = "0.7.4"
borsh = "0.9.1"
bs58 = "0.4.0"
cadence = "0.29.0"
cadence-macros = "0.29.0"
chrono = "0.4.19"
clap = { version = "4.2.2", features = ["derive", "cargo"] }
digital_asset_types = { path = "../digital_asset_types", features = ["json_types", "sql_types"] }
env_logger = "0.10.0"
figment = { version = "0.10.6", features = ["env", "toml", "yaml"] }
flatbuffers = "23.1.21"
futures = "0.3.25"
hex = "0.4.3"
log = "0.4.17"
mpl-bubblegum = "0.7.0"
num-traits = "0.2.15"
plerkle_messenger = { git = "https://github.com/rpcpool/digital-asset-validator-plugin.git", branch="add_backfill-streams", features = ["redis"] }
plerkle_serialization = "1.5.2"
rand = "0.8.5"
reqwest = "0.11.11"
rust-crypto = "0.2.36"
sea-orm = { version = "0.10.6", features = ["macros", "runtime-tokio-rustls", "sqlx-postgres", "with-chrono", "mock"] }
serde = "1.0.136"
serde_json = "1.0.81"
solana-account-decoder = "~1.14"
solana-client = "~1.14"
solana-sdk = "~1.14"
solana-transaction-status = "~1.14"
solana-program = "~1.14"
spl-account-compression = "0.1.8"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
sqlx = { version = "0.6.2", features = ["macros", "runtime-tokio-rustls", "postgres", "uuid", "offline", "json"] }
stretto = { version = "0.7", features = ["async"] }
thiserror = "1.0.31"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.7"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter", "ansi"] }
url = "2.3.1"
