[package]
name = "migration"
version = "0.6.8"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "^1", features = ["attributes", "tokio1"] }
digital_asset_types = { path = "../digital_asset_types", features = ["json_types", "sql_types"] }
enum-iterator = "1.2.0"
sea-orm-migration = { version = "0.10.6", features = ["runtime-tokio-rustls", "sqlx-postgres"] }

[patch.crates-io]
anchor-lang = { git = "https://github.com/metaplex-foundation/anchor" }
blockbuster = { git = "https://github.com/metaplex-foundation/blockbuster", branch = "1.14" }
mpl-bubblegum = { git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "update-deps" }
mpl-candy-guard = { git = "https://github.com/metaplex-foundation/mpl-candy-guard", branch = "update-deps" }
mpl-candy-machine-core = { git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "update-deps" }
mpl-token-metadata = { git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "update-deps" }
