[workspace]
members = [
  "tests/acc_forwarder",
  "tests/bgtask_creator",
  "tests/load_generation",
  "tests/show-tree",
  "tests/tree-status",
  "tests/txn_forwarder",
]

[profile.release]
lto = true
codegen-units = 1
