[workspace]
members = [
  "metaplex-rpc-proxy",
  "nft_ingester",
  "tests/acc_forwarder",
  "tests/bgtask_creator",
  "tests/load_generation",
  "tests/show-tree",
  "tests/tree-status",
  "tests/txn_forwarder",
]
exclude = [
  "dash_api",
  "digital_asset_types",
  "migration",
]

[profile.release]
lto = true
codegen-units = 1
