[package]
name = "fetch_trees"
version = "0.7.12"
edition = { workspace = true }
repository = { workspace = true }
publish = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo"] }
mpl-bubblegum = { workspace = true }
solana-account-decoder = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-account-compression = { workspace = true, features = ["no-entrypoint"] }
tokio = { workspace = true, features = ["tracing"] }

[lints]
workspace = true
