[package]
name = "digital_asset_types"
version = "0.6.8"
edition = "2021"
publish = false

[dependencies]
blockbuster = "0.7.3"
bs58 = "0.4.0"
jsonpath_lib = "0.3.0"
log = "0.4.17"
mime_guess = "2.0.4"
schemars = { version = "0.8.6", features = ["derive"] }
sea-orm = { version = "0.10.6", features = ["macros", "runtime-tokio-rustls", "sqlx-postgres", "with-chrono", "mock"], optional = true }
serde = { version = "1.0.137", optional = true }
serde_json = { version = "1.0.81", features = ["preserve_order"], optional = true }
spl-concurrent-merkle-tree = "0.1.3"
tokio = { version = "1.22.0", features = ["macros"] }
url = "2.3.1"

[dev-dependencies]
reqwest = "0.11.13"
solana-sdk = "1.14.10"

[features]
default = ["json_types", "sql_types"]
json_types = ["serde", "serde_json"]
sql_types = ["sea-orm"]
