prometheus: 127.0.0.1:8873
geyser_endpoint: http://127.0.0.1:10000
x_token: null
commitment: finalized
max_concurrency: 5
subscriptions:
  token-metadata:
    stream:
      name: !ACCOUNTS
      max_len: 100_000_000
    filter: !ACCOUNTS
      owner:
        - metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
  token-extension:
    stream:
      name: !ACCOUNTS
      max_len: 100_000_000
    filter: !ACCOUNTS
      owner:
        - TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
  token:
    stream:
      name: !ACCOUNTS
      max_len: 100_000_000
    filter: !ACCOUNTS
      owner:
        - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
  tcomp:
    stream:
      name: !ACCOUNTS
      max_len: 100_000_000
    filter: !ACCOUNTS
      owner:
        - CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d
  bubblegum-accounts:
    stream:
      name: !ACCOUNTS
      max_len: 100_000_000
    filter: !ACCOUNTS
      owner:
        - BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY
  bubblegum-transactions:
    stream:
      name: !TRANSACTIONS
      max_len: 10_000_000
    filter: !TRANSACTIONS
      account_include:
        - BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY

redis:
  url: redis://localhost:6379
  pipeline_max_size: 1_000
  pipeline_max_idle_ms: 100_000
