# prometheus metrics are pushed to this endpoint
prometheus: 0.0.0.0:8878

# postgres configuration
postgres:
  # connection url
  url: postgres://solana:solana@localhost/solana
  # min connections
  min_connections: 10
  # max connections
  max_connections: 500

# Receives batches of AccountInfo from `snapshot_write` and processes them 1 by 1.
program_transform:
  # Max amount of program transformers processing individual AccountInfo concurrently.
  # Note: In practice this will usually be the main bottleneck.
  max_workers: 200
  buffer_capacity: 1_000

# Receives AccountInfo's individually from the downloaded snapshot, batches them
#  and saves them to the `account_snapshots` table, and sends them to
#  `program_transform` in the same batches.
snapshot_write:
  # Max amount of AccountSnapshotWriter sending batches of AccountInfo to `program_transform`
  max_workers: 10
  # Channel capacity for the AccountSnapshotWriter.
  channel_capacity: 500
  batch_size: 500

# download metadata configuration for the ingester
# This receives the `DownloadMetadataInfo` with the asset and url
#  from the `program_transform` and downloads the metadata.
download_metadata:
  # Max amount of `DownloadMetadataInfo` fetched concurrently.
  metadata_json_download_worker_count: 3
  metadata_json_download_worker_request_timeout: 150

# The sidecar endpoint to download the snapshot from.
sidecar_endpoint: http://127.0.0.1:13080

# List of programs to process from the downloaded snapshot.
programs_to_process:
  - TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
