[package]
name = "txn_forwarder"
version = "0.7.12"
edition = { workspace = true }
repository = { workspace = true }
publish = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
figment = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
plerkle_messenger = { workspace = true, features = ['redis'] }
plerkle_serialization = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time", "fs"] }
tokio-stream = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
