name: Build & Test
on:
  pull_request:
    branches:
      - main
      - triton
env:
  RUST_TOOLCHAIN: stable
jobs:
  build-api:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fmt
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --tests
      - name: Build
        run: |
          cd das_api
          cargo build  --all-targets --tests
        shell: bash
  build-migration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fmt
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --tests
      - name: Build
        run: |
          cd migration
          cargo build --all-targets --tests
        shell: bash
  build-ingest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fmt
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --tests
      - name: Build
        run: |
          cargo build  --all-targets --tests
        shell: bash


