name: Build & Test
on:
  push:
  pull_request:
    branches:
      - main
env:
  RUST_TOOLCHAIN: stable
jobs:
  build-api:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd das_api
          cargo build
        shell: bash
  build-migration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd migration
          cargo build
        shell: bash
  build-ingest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build
        shell: bash


